### ISSUE TITLE
New Routing helpers: `parallel` and `sequential`.

### ISSUE THREAD

**Issue by ajnavarro** [libp2p/go-libp2p-routing-helpers#56]
We need to implement two routing helpers that will get a list of routers and execute them in parallel or sequentially:

- `sequential` router:
    - Get a list of routers. Routers will be executed in the provided order.
    - Local timeout (time.Duration) per router.
    - IgnoreError flag per router. If that router fails, the execution won't be stopped and we will try with the next router on the list.
    - Global timeout (time.Duration) that will affect the total time execution and will include all the routers.
- `parallel` router:
    - Get a list of routers. Routers will be executed in parallel.
    - Local timeout (time.Duration) per router.
    - IgnoreError flag per router. If that router fails, other routers will be still executed in parallel.
    - ExecuteAfter(time.Duration) per Router. Wait until the specified time to be executed.
    - Global timeout (time.Duration) that will affect the total time execution and will include all the routers.

**Comment by BigLep** [comment]
Per discussion on 2022-08-19, we're going to see if we can use the existing routers rather than create new ones.  

Per usuals, unit tests are expected before this is done.

**Comment by ajnavarro** [comment]
I tried to use the `Tiered` router as a start point and implement everything from there. The main problem is that will cost a fair amount of work to make it backward-compatible because it has a super specific behavior per method that will need to be the default and it is mixing sequential and parallel logics.

**Comment by BigLep** [comment]
2022-08-25 conversation: 
* Consider using generics
* If we change the semantics, make sure we document and ensure that the areas that are affected will be ok.
* We can break whatever we want, but need to communicate in the release notes

**Comment by ajnavarro** [comment]
Work being done here: https://github.com/libp2p/go-libp2p-routing-helpers/pull/58
